import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/static/Header";
import Sider from "./static/Sider";
import { GlobalContext, GlobalProvider } from "@/global/GlobalProvider";

import MainSider from "./static/MainSider";
import Context from "./static/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <section className="flex">
            <MainSider />
            <div className="w-full">
              <Context>{children}</Context>
            </div>
          </section>
        </GlobalProvider>
      </body>
    </html>
  );
}
